### ISSUE TITLE
Enhanced reporting France

### ISSUE THREAD

**Issue by hef-abd** [sociepy/covid19-vaccination-subnational#10]
The initial source is discontinued and current data is found here: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19-1/#_

Specifically:
- 1st dose: https://www.data.gouv.fr/fr/datasets/r/735b0df8-51b4-4dd2-8a2d-8e46d77d60d8
- 2nd dose: https://www.data.gouv.fr/fr/datasets/r/96db2c1a-8c0c-413c-9a07-f6f62f3d4daf

Watch out for the column names: they are the same, but the descriptions of the files mention 1st and 2nd. 

Current sourcehas been discontinued otherwise.

**Comment by lucasrodes** [comment]
Thanks for the info @hef-abd, really appreciate it!

Are you planning on adding this feature or may I work on this later? Thanks!

**Comment by lucasrodes** [comment]
Hi @hef-abd,
I am trying to understand these data sources. The names are confusing to me. The second file seems it provides data segregated by sex, but not sure it actually does.

Take, for instance, `reg=0` and `date=2021-01-12`. In first file, we have that `n_dose1=20`. In the second we have `n_dose1=20` and `n_dose1=14` for `sex=0` and `sex=1`, respectively. Not sure how to verify what this actually means.

**Comment by hef-abd** [comment]
I was just playing with the data and found some weird things, then went to read the discussion below; it seems it has not been stable over the last couple of days (disappearing columns and non-adding-up numbers), probably worth putting on hold until it's clearer; got excited too fast about it !

**Comment by lucasrodes** [comment]
No problem, appreciate your report, now at least I know the current source is deprecated 😄 

From what I see, the only file containing dose 2 info is [`vacsi-tot-reg-2021-01-31-20h15.csv`](https://www.data.gouv.fr/fr/datasets/r/9b1e6c8c-7e1d-47f9-9eb9-f2eeaab60d99), which however only contains data of last day and is not consistent with the data that the project is currently using.

Take `reg=1` (Gadeloupe), which has `n_tot_dose1=707` for 2021-01-30. In the current data source, we have 1299 doses for 2021-01-24 (extracted from [old reference](https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-personnes-vaccinees-contre-la-covid-19/)).

I guess we need to wait or reach out to someone responsible for this data.

**Comment by lucasrodes** [comment]
For the time being,
I have decided to join different resources in order to create a more accurate dataset:

- 1 dose: [https://www.data.gouv.fr/fr/datasets/r/735b0df8-51b4-4dd2-8a2d-8e46d77d60d8](https://www.data.gouv.fr/fr/datasets/r/735b0df8-51b4-4dd2-8a2d-8e46d77d60d8)
- 2 dose: [https://geodes.santepubliquefrance.fr/index.php#c=indicator&f=0&i=vacsi_tot_a.n_tot_dose1&s=2021-01-30&t=a01&view=map1](https://geodes.santepubliquefrance.fr/index.php#c=indicator&f=0&i=vacsi_tot_a.n_tot_dose1&s=2021-01-30&t=a01&view=map1)

Finally, I'll be updating it incrementally using file [vacsi-tot-reg-2021-01-31-20h15.csv](https://www.data.gouv.fr/fr/datasets/r/9b1e6c8c-7e1d-47f9-9eb9-f2eeaab60d99)
